### ISSUE TITLE
index.html "learn about me here" button

### ISSUE THREAD

**Issue by smilleeymilleey** [smilleeymilleey/Portfolio#3]
-the shadow is too large for the white button

<img width="352" alt="Screen Shot 2019-09-28 at 11 59 30 AM" src="https://user-images.githubusercontent.com/55720093/65819889-7a79ac00-e1e7-11e9-8988-7c3b734c9d0e.png">

**Comment by chrisplatorres** [comment]
You are using the div here, so the style of the id  `about-me-button` is styling the div, try using the id `about-me-button` in the button. 

https://github.com/smilleeymilleey/Portfolio/blob/9cfe5f29f29de124b93cc9080bfffea30b41e276/index.html#L36


the styling for the id:
https://github.com/smilleeymilleey/Portfolio/blob/9cfe5f29f29de124b93cc9080bfffea30b41e276/index.html#L19-L23

**Comment by smilleeymilleey** [comment]
fixed! 
c1eb156
